import { eventBus } from './EventBus.js';

export const GAME_STATES = {
  BOOT: 'BOOT',
  TITLE: 'TITLE',
  SELECTION: 'SELECTION',
  PLAYING: 'PLAYING',
  SLOW_MOTION_MENU: 'SLOW_MOTION_MENU',
  MODIFIER_SELECTION: 'MODIFIER_SELECTION',
  EQUIPMENT: 'EQUIPMENT',
  PAUSED: 'PAUSED',
  TRANSITION: 'TRANSITION',
  STAGE_CLEAR: 'STAGE_CLEAR',
  GAME_OVER: 'GAME_OVER'
};

const VALID_TRANSITIONS = {
  [GAME_STATES.BOOT]: [GAME_STATES.TITLE],
  [GAME_STATES.TITLE]: [GAME_STATES.SELECTION, GAME_STATES.PLAYING, GAME_STATES.EQUIPMENT, GAME_STATES.TRANSITION],
  [GAME_STATES.SELECTION]: [GAME_STATES.PLAYING, GAME_STATES.TITLE, GAME_STATES.PAUSED, GAME_STATES.EQUIPMENT, GAME_STATES.SLOW_MOTION_MENU],
  [GAME_STATES.PLAYING]: [GAME_STATES.PAUSED, GAME_STATES.SLOW_MOTION_MENU, GAME_STATES.MODIFIER_SELECTION, GAME_STATES.STAGE_CLEAR, GAME_STATES.GAME_OVER, GAME_STATES.TRANSITION, GAME_STATES.EQUIPMENT, GAME_STATES.SELECTION],
  [GAME_STATES.SLOW_MOTION_MENU]: [GAME_STATES.PLAYING, GAME_STATES.PAUSED, GAME_STATES.MODIFIER_SELECTION, GAME_STATES.SELECTION, GAME_STATES.EQUIPMENT, GAME_STATES.GAME_OVER],
  [GAME_STATES.MODIFIER_SELECTION]: [GAME_STATES.PLAYING, GAME_STATES.SLOW_MOTION_MENU, GAME_STATES.PAUSED],
  [GAME_STATES.EQUIPMENT]: [GAME_STATES.TITLE, GAME_STATES.PLAYING, GAME_STATES.SELECTION, GAME_STATES.PAUSED, GAME_STATES.SLOW_MOTION_MENU],
  [GAME_STATES.PAUSED]: [GAME_STATES.PLAYING, GAME_STATES.TITLE, GAME_STATES.EQUIPMENT, GAME_STATES.SELECTION, GAME_STATES.SLOW_MOTION_MENU],
  [GAME_STATES.STAGE_CLEAR]: [GAME_STATES.TRANSITION, GAME_STATES.TITLE, GAME_STATES.GAME_OVER, GAME_STATES.SELECTION],
  [GAME_STATES.TRANSITION]: [GAME_STATES.TITLE, GAME_STATES.PLAYING, GAME_STATES.EQUIPMENT, GAME_STATES.GAME_OVER, GAME_STATES.SELECTION, GAME_STATES.STAGE_CLEAR],
  [GAME_STATES.GAME_OVER]: [GAME_STATES.SELECTION, GAME_STATES.TITLE, GAME_STATES.PLAYING, GAME_STATES.TRANSITION]
};

class GameStateManager {
  constructor() {
    this.state = GAME_STATES.BOOT;
    this.previousState = null;
  }

  canTransitionTo(newState) {
    if (!VALID_TRANSITIONS[this.state]) return false;
    return VALID_TRANSITIONS[this.state].includes(newState);
  }

  setState(newState) {
    if (this.state === newState) return;
    if (!this.canTransitionTo(newState)) {
      console.warn(`Invalid state transition: ${this.state} -> ${newState}`);
      return;
    }
    
    this.previousState = this.state;
    this.state = newState;
    
    eventBus.emit('state:changed', {
      state: this.state,
      previousState: this.previousState
    });
  }

  is(state) {
    return this.state === state;
  }

  dispose() {
    this.state = GAME_STATES.BOOT;
    this.previousState = null;
  }
}

export const gameStateManager = new GameStateManager();
